name: chrome
description: "Open google.com with Chrome and close the browser"
enabled: true
max_execution: 3
variables:
  args: https://google.com
linux-cmd: chrome $args
macos-cmd: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome $args
windows-cmd: chrome $args
